import { Badge } from "@/components/ui/badge";
import { AlertTriangle, Shield, Stethoscope, FileWarning } from "lucide-react";
import { Seo } from "@/components/Seo";

const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-white">
      <Seo
        title="Medical Disclaimer"
        description="Important medical disclaimer for professional users of GenzAI Labs software — intended use, limitations, and regulatory status."
        path="/disclaimer"
      />
      <section className="bg-gradient-to-br from-blue-50 via-white to-cyan-50 py-20">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <Badge className="mb-4 bg-yellow-100 text-yellow-800 hover:bg-yellow-200">
            Medical Disclaimer
          </Badge>
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Important Notice
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Please read this disclaimer carefully before using any GenzAI Labs
            product or service.
          </p>
        </div>
      </section>

      <section className="py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
          <div className="bg-yellow-50 border-l-4 border-yellow-500 p-6 rounded-r-lg">
            <div className="flex items-start space-x-3">
              <AlertTriangle className="h-6 w-6 text-yellow-600 flex-shrink-0 mt-1" />
              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-2">
                  For Professional Use Only
                </h2>
                <p className="text-gray-700 leading-relaxed">
                  GenzAI Labs products are intended solely for use by qualified
                  medical professionals, including radiologists, neurologists,
                  and clinicians trained in medical image interpretation. They
                  are not intended for use by patients or the general public.
                </p>
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <Stethoscope className="h-6 w-6 text-blue-600" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-3">
                  Clinical Decision Support Only
                </h2>
                <p className="text-gray-700 leading-relaxed">
                  All outputs generated by GenzAI Labs software — including
                  perfusion maps, ASPECTS scores, tumor classifications, and
                  screening flags — are provided as clinical decision support.
                  They are <strong>not</strong> standalone diagnostic devices
                  and must always be interpreted alongside the full clinical
                  context, patient history, and other diagnostic information by
                  a qualified professional.
                </p>
              </div>
            </div>

            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <FileWarning className="h-6 w-6 text-blue-600" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-3">
                  No Guarantee of Accuracy
                </h2>
                <p className="text-gray-700 leading-relaxed">
                  While GenzAI Labs strives to provide accurate and reliable
                  analyses, we do not guarantee the completeness, accuracy, or
                  reliability of automated outputs. Variability in input data,
                  scanner protocols, patient physiology, imaging conditions,
                  and other factors may affect results. Outputs should be
                  independently verified before any clinical decision.
                </p>
              </div>
            </div>

            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <Shield className="h-6 w-6 text-blue-600" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-3">
                  Limitation of Liability
                </h2>
                <p className="text-gray-700 leading-relaxed">
                  GenzAI Labs Pvt Ltd and its affiliates shall not be held
                  responsible or liable for any consequences — including but
                  not limited to misdiagnosis, delayed diagnosis, or incorrect
                  treatment decisions — resulting from the use of our software.
                  The user assumes all risks associated with the use of the
                  software and its outputs.
                </p>
              </div>
            </div>

            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <AlertTriangle className="h-6 w-6 text-blue-600" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-3">
                  Regulatory Status
                </h2>
                <p className="text-gray-700 leading-relaxed">
                  GenzAI Labs products are undergoing ongoing clinical
                  validation. Regulatory clearance varies by region and product.
                  Please contact us directly to confirm current regulatory
                  status before clinical deployment in your jurisdiction. Use
                  outside validated clinical contexts is at the user's own
                  risk.
                </p>
              </div>
            </div>
          </div>

          <div className="bg-gray-50 rounded-lg p-6 border border-gray-200 mt-10">
            <p className="text-sm text-gray-600">
              For questions about intended use, regulatory status, or clinical
              validation studies, please contact us at{" "}
              <a
                href="mailto:doc@genzailabs.com"
                className="text-blue-600 hover:underline"
              >
                doc@genzailabs.com
              </a>
              .
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Disclaimer;
